Convert Go regex to Rust regex
GreptimeTeam/promql-parser pull request #76
Opened 2023-10-30 23:05 UTC by fbs

Go and Rust have some differences in their regex implementation. In Go the following is valid:

```
uri=~"/v[1-9]/.*/{gid}/{uid}"
```

Rust sees the `{gid}` as a bad repetition, it expects a range like {1,4}

```
regex parse error:
    /v[1-9]/.*/{gid}/{uid}
                ^
error: repetition quantifier expects a valid decimal
```

For it to be a valid Rust regex the opening { has to be escaped.

This change adds that escaping.

The implementation is simple, iteration + writing in a result buffer. It is probably not the best of nicest way of doing it, but it straight forward.

Fixes #75

2023-10-31 01:46 UTC, yuanbohan commented
Hi, thanks for your contribution :+1: 
Could you fix the clippy error? and you can refer #77, or you can rebase the main branch after the PR #77 is merged

2023-10-31 02:15 UTC, yuanbohan requested changes

2023-10-31 02:15 UTC, yuanbohan commented on src/label/matcher.rs
> +            if c == '\\' {
If `c == '\\'` branch is placed under `if c != '{'`, it is better for review?

2023-10-31 02:15 UTC, yuanbohan commented on src/label/matcher.rs
> +        assert_eq!(convert("abc{1,,2}"), r#"abc\{1,,2}"#);
what about `abc{}`?

2023-10-31 02:15 UTC, yuanbohan commented on src/label/matcher.rs
> +                    if comma || buf.len() == 1 {
maybe `buf == ","` is easier for understanding than `len == 1`?

2023-10-31 02:15 UTC, yuanbohan commented on src/label/matcher.rs
> +        // (true, string) if its a valid repeat pattern (e.g. 1,2 or ,3)
`,3` is not repeat?

2023-10-31 02:15 UTC, yuanbohan commented on src/label/matcher.rs
> +        fn is_repeat(chars: &mut std::str::Chars<'_>) -> (bool, String) {
In other words, only `{\d+,\d+}` is repetition, otherwise return false?

2023-10-31 11:55 UTC, fbs commented on src/label/matcher.rs
> +        assert_eq!(convert("abc{1,,2}"), r#"abc\{1,,2}"#);
ah good one

2023-10-31 11:59 UTC, fbs commented on src/label/matcher.rs
> +            if c == '\\' {
not sure if it is, but can do it if you prefer

2023-10-31 14:29 UTC, yuanbohan approved these changes

2023-11-03 03:12 UTC, v0y4g3r commented
Looks like we only need to convert the `{` characters without preceding  backslash `\` to `\{` while remove the preceding `\` from `\{` in Golang regex to make it work in Rust regex. 

The problem is the difference between Go and Rust in handling repetition sequence and bracket literal. Go treats `{` as 
bracket literal while Rust treats `{` as the start of repetition sequence.

For example, for `/v[1-9]/.*/{gid}/{uid}` in Golang, the corresponding Rust regex would be `/v[1-9]/.*/\{gid\}/\{uid\}`: https://regex101.com/r/k7b6N8/1

2023-11-03 11:54 UTC, fbs commented
Yes thats basically what this MR does, Go 'auto escapes' the sequence while Rust doesn't. So the conversion is `a{aa}` -> `a\{aa}` but `a{1,2}` stays `a{1,2}`

2023-11-06 03:49 UTC, waynexia commented
> Yes thats basically what this MR does, Go 'auto escapes' the sequence while Rust doesn't. So the conversion is `a{aa}` -> `a\{aa}` but `a{1,2}` stays `a{1,2}`

Should `a{aa}` goes to `a\{aa\}`? `}` needs escaping as well.

2023-11-06 07:10 UTC, yuanbohan commented
> > Yes thats basically what this MR does, Go 'auto escapes' the sequence while Rust doesn't. So the conversion is `a{aa}` -> `a\{aa}` but `a{1,2}` stays `a{1,2}`
> 
> Should `a{aa}` goes to `a\{aa\}`? `}` needs escaping as well.

I'm interested in the escaping of `}`, maybe it does not affect the result if the regex does not find the starting of repetition pattern?

2023-11-06 15:20 UTC, fbs commented
I'm not entirely sure what you mean. In my testing just escaping the `{` is enough. A `}` without leading (or with escaped) `{` is just seen as a literal


```
$ cat src/main.rs
use regex::Regex;

fn main() {
    let re = Regex::new(r"a}a\{a}").unwrap();
    let Some(caps) = re.captures("a}a{a}") else {
        println!("no match!");
        return;
    };
    println!("The name is: {:?}", caps);
}

/tmp/regex master[?] $ cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/regexxx`
The name is: Captures({0: 0..6/"a}a{a}"})
```

2023-11-07 08:34 UTC, merged

2023-11-07 08:34 UTC, waynexia commented
Thanks for your contribution @fbs :heart:

2023-11-07 09:17 UTC, fbs commented
Thanks for the quick review team! <3. 

I wonder if there are more regex incompatibility issues in this.

2023-11-07 23:46 UTC, yuanbohan commented
> Thanks for the quick review team! <3. 
> 
> I wonder if there are more regex incompatibility issues in this. 

I will watch on this, thanks for your contribution 😀